### ISSUE TITLE
BUG: local variable 'trans_constr' referenced before assignment

### ISSUE THREAD

**Issue by venaturum** [Gurobi/gurobi-machinelearning#167]
Originally posted to community forum
[https://support.gurobi.com/hc/en-us/community/posts/15116202641425](https://support.gurobi.com/hc/en-us/community/posts/15116202641425)

The error is coming from these lines:

https://github.com/Gurobi/gurobi-machinelearning/blob/88f953c7b17e4d3c9168dc10b0ad1a270f4112f2/src/gurobi_ml/sklearn/column_transformer.py#LL76C1-L80C1

Not sure if it's a case of missing line or wrong indentation or something else.

**Comment by pobonomo** [comment]
Thanks for opening the issue.
It was missing properly handling the error.
