### ISSUE TITLE
Avoid using addGenConstrLogistic when doing classification with Logistic Regression

### ISSUE THREAD

**Issue by venaturum** [Gurobi/gurobi-machinelearning#316]
Currently to do classification we round the output of logistic regression:

$\frac{1}{1 - e^{-f(x)}}$

where f(x) is the affine transformation defined by the trained logistic regression model.

![image](https://github.com/Gurobi/gurobi-machinelearning/assets/51399800/f7054434-2cbe-4180-b078-c3025614fbcd)

For classification it seems it would be enough to use indicator constraints on the result of f(x), i.e. whether `affinevars` are negative or positive, and then we don't need to introduce non-linearity via addGenConstrLogistic.

Does this seem right?

 \- Riley

**Comment by pobonomo** [comment]
Hi Riley,
Yes, you are completely right. We could (and should) save adding the nonlinear constraint by using indicator variables.

**Comment by venaturum** [comment]
No issues (excuse the pun) with me having a go at a PR?

**Comment by pobonomo** [comment]
Not at all. On the contrary, more than happy if you can do it. And if you need any help let me know.

**Comment by pobonomo** [comment]
FIxed by #318
